[package]
name = "zip_directories"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rayon = "1.5.0"
zip = "0.5.8"
glob = "0.3"
walkdir = "2.3.2"